# Generated by Django 2.2.4 on 2019-09-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0005_auto_20190905_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='article',
            field=models.ManyToManyField(related_name='tags', related_query_name='tag', to='apiv1.Article', verbose_name='タグ'),
        ),
    ]
