# Generated by Django 2.2.4 on 2019-09-05 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0006_auto_20190905_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='tagname',
        ),
    ]
